language: python
python:
  - "2.7"

env:
  - DJANGO_VERSION=1.8

install:
  - pip install codecov
  - pip install -q Django==$DJANGO_VERSION
  - pip install -q -r requirements.txt

script:
  - coverage run sample/manage.py test renderer
  - coverage run sample/manage.py test demo

after_success:
  - codecov
