language: python

python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

env:
  - DJANGO_VERSION=1.7
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.9b1

install:
  - pip install codecov
  - pip install -q Django==$DJANGO_VERSION
  - pip install -q -r requirements.txt

script:
  - coverage run sample/manage.py test demo renderer

after_success:
  - codecov
